version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install -g typescript@4.5.5
      - npm install
  build:
    commands:
      - tsc
      - cp -r ./src/templates/ ./build/templates

artifacts:
  files:
    - Procfile
    - package.json
    - package-lock.json
    - 'build/**/*'
    - '.ebextensions/**/*'
    - '.platform/**/*'
  discard-paths: no
