version: "3.7"

services:
  redis:
    image: redis:latest
    command: redis-server
    env_file:
      - ./.env
    expose:
      - "6379"
    ports:
      - 6379:6379

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./.env
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
