export const NOTIFICATION_FOLLOW = 'FOLLOW';
export const NOTIFICATION_EVENT_INVITE = 'EVENT_INVITE';
export const NOTIFICATION_COMMUNITY_INVITE = 'COMMUNITY_INVITE';
export const NOTIFICATION_NEW_LIKE = 'NEW_LIKE';
export const NOTIFICATION_NEW_COMMENT = 'NEW_COMMENT';
export const NOTIFICATION_POST_REPORT = 'POST_REPORT';
export const NOTIFICATION_COMMUNITY_REPORT = 'COMMUNITY_REPORT';

export const NOTIFICATION_TYPES = [
  NOTIFICATION_FOLLOW,
  NOTIFICATION_EVENT_INVITE,
  NOTIFICATION_COMMUNITY_INVITE,
  NOTIFICATION_NEW_LIKE,
  NOTIFICATION_NEW_COMMENT,
  NOTIFICATION_POST_REPORT,
  NOTIFICATION_COMMUNITY_REPORT,
];
